# Generated by Django 3.0.7 on 2020-07-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20200702_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='start_time',
            field=models.DateTimeField(unique_for_date=True, unique_for_month=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='surname',
            field=models.CharField(max_length=200, unique=True, verbose_name='Фамилия'),
        ),
    ]
