# Generated by Django 3.0.7 on 2020-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20200702_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='start_time',
            field=models.DateTimeField(unique=True, verbose_name='Дата регистрации'),
        ),
    ]
