# Generated by Django 3.0.7 on 2020-07-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20200702_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
    ]
