# Generated by Django 3.0.7 on 2020-07-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20200702_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name_plural': 'Читатели '},
        ),
    ]
